# Server
server.port=${PORT:10000}

# MongoDB
# This uses the Render variable first, and only uses localhost if the variable is missing
spring.data.mongodb.uri=mongodb://teomw02_db_user:cFnD2AZbMtAfvzRP@ac-r4z2i8t-shard-00-00.kg3cwoq.mongodb.net:27017,ac-r4z2i8t-shard-00-01.kg3cwoq.mongodb.net:27017,ac-r4z2i8t-shard-00-02.kg3cwoq.mongodb.net:27017/?ssl=true&replicaSet=atlas-12zbkg-shard-0&authSource=admin&appName=Cluster0
spring.data.mongodb.database=taskmanager
spring.data.mongodb.auto-index-creation=true

# Security
jwt.secret=${JWT_SECRET:mySecretKeyForJWTTokenGenerationPleaseChangeThisInProduction}
jwt.expiration=86400000

# Logging (Helps you see the real error next time)
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG